name: Deploy to EC2

on:
  push:
    branches:
      - main # או master, תלוי בשם הבראנץ' הראשי שלך

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER || 'ubuntu' }} # ישתמש ב-EC2_USER אם הוגדר, אחרת 'ubuntu'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          
          cd /home/ubuntu/ProjectSubmission/homeWork
          git pull
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r build/ /var/www/html